### PR TITLE
Changed target sdk and Fix#10

### LINKED ISSUE #10: Fix bugs in color spaces to enable showing RGBA data in Bitmap
There is some little bugs I'll fix with this issue (our you could try to fix it).

`matToBitmap` is not working because image sizes and color depth must be the same.

I had to make the "pull request" with erroneous code to share with you the way to implement OpenCV functionality.

### PR DESCRIPTION
**Pull request by gsssrao**
Changed target sdk and Fix #10

### CODE REVIEW

**Comment by gsssrao** [comment]
Changed target sdk as 21 was creating a problem. 
Also, made the canny filter

**Comment by ojgarciab** [comment]
Sorry, canny filter doesn't work for me. Only using another mobile, if using cameraserver it doesn't work.

**Comment by gsssrao** [comment]
Fix #14

**Comment by ojgarciab** [comment]
You forgot change `project.properties`. Now all is right.

**Pull request merged**
